dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: yoWucChgYfmQwYpYkMqP
  - secure: donovanmuller
  - secure: yoWucChgYfmQwYpYkMqP
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
